### ISSUE TITLE
How to enable USB-C (front panel)?

### ISSUE THREAD

**Issue by sowson** [czombos/asus-rog-strix-z390-i-gaming#10]
Hello @czombos,

Can you help me with this? Is it possible to enable front panel USB-C without disabling anything else? I am using the NCase M1 case that has a front panel USB-C that does not work. It is connected to the motherboard by a cable.

Thanks!

**Comment by czombos** [comment]
Make a new USBMap: https://github.com/corpnewt/USBMap
More info: https://usb-map.gitbook.io/project/

**Comment by sowson** [comment]
Hello, please help me… how did you found PciRoot for key value:

                        <key>PciRoot(0x0)/Pci(0x1C,0x7)/Pci(0x0,0x0)</key>
                        <dict>
                                <key>AAPL,slot-name</key>
                                <string>WLAN</string>
                                <key>compatible</key>
                                <string>pci14e4,4331</string>
                                <key>device_type</key>
                                <string>Airport Extreme</string>
                                <key>model</key>
                                <string>Dell DW1820A 802.11ac wireless</string>
                                <key>name</key>
                                <string>Airport</string>
                                <key>pci-aspm-default</key>
                                <integer>0</integer>
                        </dict>

Is USBMap could make DW1820A affected? I am trying on different Asus z390-e MoBo…

Thanks!
