### ISSUE TITLE
Is it possible to encrypt TimeMachine backups?

### ISSUE THREAD

**Issue by sowson** [czombos/asus-rog-strix-z390-i-gaming#11]
Hello @czombos,

Can you help me with this? I assume it is not possible once there is not a "security chip" on the motherboard, but please correct me if I am wrong.

Thanks!

**Comment by czombos** [comment]
It works.
Please read this: https://support.apple.com/guide/mac-help/choose-a-backup-disk-set-encryption-options-mh11421/10.15/mac/10.15
