### ISSUE TITLE
Does not define a graphics card

### ISSUE THREAD

**Issue by alex-pol** [czombos/asus-rog-strix-z390-i-gaming#13]
Hi, can you please help. I have i5 9400f processor without UDH graphics and have radeon RX 550 card, but os does not correct define the card.
![unnamed](https://user-images.githubusercontent.com/8250032/76706885-e8fde800-66fb-11ea-9a05-66c5c8cd615c.jpg)

**Comment by alex-pol** [comment]
Found a solution to add faked device id. I know how to do it in clover, but I don't know how to do it in opencore. Can you help?

**Comment by czombos** [comment]
RX 550 not supported is macOS:
https://khronokernel-3.gitbook.io/gpu-buyers-guide/modern-gpus/amd-gpu#unsupported-amd-gpus

Read this guides:
https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/blob/master/extras/hardware.md
