### ISSUE TITLE
Apple TV does not work, can you help me? I do not know why... it doest not work?

### ISSUE THREAD

**Issue by sowson** [czombos/asus-rog-strix-z390-i-gaming#14]
This is my fork... https://github.com/sowson/hackintosh Thank you because I think you are true Hacker... I can only dream to be on that level, to understand OC like you! Really!

**Comment by sowson** [comment]
Anyway, I prefer HBO / HBO GO and that works on Chrome... Apple TV: $49 Frozen? Just a joke once DVD cost is less than 40 PLN... sorry you may close the issue once IMHO Apple TV is too expensive...

**Comment by sowson** [comment]
I "follow the master" updated all (from you, but not yet on my fork) and TV is the only app that does not work (I put only each WLAN things)... pls help I am using macOS 10.15.4, should I roll back to 10.15.3 where TV was fine?

**Comment by MilesWuCode** [comment]
> I "follow the master" updated all (from you, but not yet on my fork) and TV is the only app that does not work (I put only each WLAN things)... pls help I am using macOS 10.15.4, should I roll back to 10.15.3 where TV was fine?

I can watch AppleTV!!
- Radeon RX 590

**Comment by sowson** [comment]
I am using 4k 15.4 inch panel from 'unperfect' company, this may be the case I order ’standard’ monitor and we gonna see how it works once I get it. Please keep till that time issue open. Thx!

**Comment by sowson** [comment]
Thanks, I bought FullHD LG 24'' Monitor and rollback one DRM fix on my fork and Apple TV works great! Look on the last commit on the https://github.com/sowson/hackintosh I am closing this issue.
