### ISSUE TITLE
Settlers 4 from GOG on CodeWave CrossOver-19.0.0

### ISSUE THREAD

**Issue by sowson** [czombos/asus-rog-strix-z390-i-gaming#15]
@czombos it is probably the minor issue but I do not know how to fix it... and I love Settlers4 :D.

I try to run on my fork at https://github.com/sowson/hackintosh I am following this repo all is updated except WLAN... once I have different solutions.

Also, I hacked the Settlers IV in the way from my blog https://iblog.isowa.io/2015/03/28/settlers-iv-pl-on-macbook-pro-in-fullscreen-1610/ to run on 1920x1080 resolution, but it does not work... only 800x600...

I know that this is a minor issue but this is my super cool game ever :D...

On MacBook Pro 13'' Retina it works as well on Catalina 10.15.4 no issue and full screen... like on this entry on my blog... https://iblog.isowa.io/2017/07/20/settlers-iv-pl-macbook-pro-13-retina/ so something is wrong with our Hackintoshes and I do not know the root cause...

My monitor is LG ELECTRONICS Monitor 24’’ 24MK600M-B I am connected to Radeon VII via HDMI

Any help welcome, thanks a lot for this solution! Even if you do not have an idea maybe someone from community knows... thanks!

**Comment by czombos** [comment]
Unfortunately, I have no experience at all with using CrossOver.

**Comment by sowson** [comment]
No worries if you do not mind I will keep the issue open maybe I find a solution... it looks like the old game is unable to properly detect the screen resolution... via HDMI... but how to fix... I will try to figure out... Thanks!

**Comment by sowson** [comment]
@czombos one more point my monitor "thing" there is no signal to it from HDMI and every (I think) 2 hours it wants to disable because "no signal" to it... so something maybe in power management in general... I am still looking for this guess. Thanks!

**Comment by czombos** [comment]
I don't know exactly what the problem might be but DisplayPort works better on macOS. Use a DisplayPort -> HDMI adapter if there is no DisplayPort connection on the monitor.

**Comment by sowson** [comment]
@czombos I used adapter DisplayPort -> HDMI very good class from DELOCK... no change at all, monitor also after a few hours disabling. Please if you do not mind, to not close this issue, because it is very interesting.

**Comment by sowson** [comment]
Than you! This bug was already solved by solved https://github.com/czombos/asus-rog-strix-z390-i-gaming-hackintosh/issues/23 :-).
