### ISSUE TITLE
System has POSTed in safe mode

### ISSUE THREAD

**Issue by kwuster** [czombos/asus-rog-strix-z390-i-gaming#18]
@Korvenwin you can look at the following [guide](https://dortania.github.io/OpenCore-Desktop-Guide/) for details on OpenCORE.

You should just be able to drag and drop @czombos OpenCORE EFI in the EFI partition on the booting drive and it should work 95%. You'll need to change your Platform SMBIOS stuff and the USBMap to match your hardware. All are detailed in the "[Dortania](https://dortania.github.io/OpenCore-Desktop-Guide/)" guide.

> One stranger thing I've noticed is after get this error and doing a Shutdown from the Apple Menu, My BIOS gives me a "System has POSTed in safe mode" error and request to press F1 Setup.

This is a strange one, and I am still trying to find ways around it, but not have the time. Ever since I updated to the latest [BIOS 2603](https://www.asus.com/Motherboards/ROG-STRIX-Z390-I-GAMING/HelpDesk_BIOS/), and used the additional fixes found relating to USB Sleep/ Shutdown from [@simoncoulton](https://github.com/simoncoulton/opencore-asus-rog-strix-z390i), I found this to be less frequent, but I don't think this is the fix as it comes back every now and then.

My research has pointed me to an RTC (Real-time clock) issue coming from MacOS 10.15.4. The issue arose due to something MacOS is writing additional 'stuff' to the RTC memory at boot.

The general consensus to use [RTCMemoryFixup.kext](https://www.asus.com/Motherboards/ROG-STRIX-Z390-I-GAMING/HelpDesk_BIOS/) if you are using 10.15.4. RTCMemoryFixup blocks/ offsets the RTC memory address space to stop MacOS from writing to them. It's a hack, a real fix would come in the from of a BIOS firmware customisation.

You might also look at the patches inside the [Sample.plist](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Sample.plist) from the OpenCorePkg repo relating to "RTC".

Again, these are the directions I am looking to take, but not yet had time to investigate fully. I've just live with it for now by setting my BIOS to **not** require 'F1' when POST failed. Of course, at your own risk. I'm starting a new issue based on this as it is off-topic.

_Originally posted by @kwuster in https://github.com/czombos/asus-rog-strix-z390-i-gaming-hackintosh/issues/16#issuecomment-619519499_

**Comment by kwuster** [comment]
The following forum lists the potential cause for the 300 series MBs failing POST & and potential fix for the issue:
[https://github.com/acidanthera/bugtracker/issues/765#issuecomment-615905137](https://github.com/acidanthera/bugtracker/issues/765#issuecomment-615905137)

Temporary Fix is the form of writing to the NVRAM the following variable via the Terminal as superuser do (sudo).
```
sudo nvram wake-failure=%00%00%00%00%00
```
I am skeptical of this one, as resetting the NVRAM via OpenCore will inevitably clear the variable, requiring its recreation after wards.

Will report if this indeed fixes the issue, albeit temporally.

**Comment by czombos** [comment]
I added <58 59> in 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:rtc-blacklist
and DisableRtcChecksum=true and AppleRtcRam=true

**Comment by kwuster** [comment]
Thanks @czombos. RTC checksum and RTC blacklist with AppleRtcRam combo has resolved the POST issues. I was 95% sure it was RTC related. I came from clover, and wasn't familiar with how OC dealt with RTCs. This clarifies a lot. Thanks.

**Comment by LeCaoDat** [comment]
@czombos thank you

**Comment by barrychum** [comment]
@czombos @kwuster 
Thanks for the help.  You saved my day!

**Comment by Josnel** [comment]
PLEASE HELP!!!
I have Asus Z490 Prime A, this doesn't work for me. It still restart after some lines and comes back to the F1 safe mode. What should I try next?

Here is my config

[Config.txt](https://github.com/czombos/asus-rog-strix-z390-i-gaming-hackintosh/files/6009206/Config.txt)
