### ISSUE TITLE
Please Help me with PciRoot of Dell DW1820A 802.11ac on Asus Z390-E Gaming

### ISSUE THREAD

**Issue by sowson** [czombos/asus-rog-strix-z390-i-gaming#22]
Hello, please help me… how did you found PciRoot for key value. I am sorry to ask on different motherboard I do not know how to obtain it...

    <key>PciRoot(0x0)/Pci(0x1C,0x7)/Pci(0x0,0x0)</key>
    <dict>
        <key>AAPL,slot-name</key>
        <string>WLAN</string>
        <key>compatible</key>
        <string>pci14e4,4331</string>
        <key>device_type</key>
        <string>Airport Extreme</string>
        <key>model</key>
        <string>Dell DW1820A 802.11ac wireless</string>
        <key>name</key>
        <string>Airport</string>
        <key>pci-aspm-default</key>
        <integer>0</integer>
    </dict>

Is USBMap could make DW1820A affected? Thanks, appreciate your help!

**Comment by peternguy3n** [comment]
You could download Hackintool to lookup the key. It has a PCIe tab that lists all of the devices.

**Comment by sowson** [comment]
And what it means if Hackintool does not show me anything from Dell od Broadcom on a PCIe tab? Did I replace / connect the BT-WLAN card wrong? ;-/.

**Comment by czombos** [comment]
Do you see the device in the bios?
https://github.com/czombos/asus-rog-strix-z390-i-gaming-hackintosh/blob/master/images/bios/JPEG/191214125833.jpg

**Comment by sowson** [comment]
I have only one combined option Bluetooth & Wireless, so I think, yes I have option in BIOS.

**Comment by peternguy3n** [comment]
Did you map your USB ports yet? I initially had WiFi but no Bluetooth until I did my own mapping because Bluetooth was on port HS14. HS14 was over the 15 port count at the time and not read by the system. Since you have a different motherboard you should try mapping your own USBs if you haven’t already.

**Comment by sowson** [comment]
It is a shame :-), but I install on another SSD Windows 10 but it not recognize the BT-WLAN card as well... is that mean it is broken? Btw, in UEFI/BIOS I have this "Bluetooth & Wireless" "Enable". Any idea? Thanks in advance!

**Comment by peternguy3n** [comment]
Is it the same Fenvi card in this build? If so, you need to download and install the drivers for it to work on windows 10.

**Comment by sowson** [comment]
I will try on the evening install the driver from the DELL site I found. Thanks for that!

**Comment by sowson** [comment]
I bought PCI-E card Fenvi and the problem has been solved :D. Thanks!
