### ISSUE TITLE
Is it possible on i9-9900k use iGPU?

### ISSUE THREAD

**Issue by sowson** [czombos/asus-rog-strix-z390-i-gaming#23]
When I am trying exactly this configuration... each time I am trying boot connected to iGPU there is a reboot in the middle of loading... "Apple Logo" ;-). Do you know how to use iGPU? Thanks!

**Comment by kwuster** [comment]
@sowson, you'll likely need to use a different smbios. This is because this SMBIOs (iMac19,1) expects a 'connector-less' iGPU. i.e. the real iMac 19,1 does not have an HDMI or DisplayPort dedicated to the iGPU. You will need to find an SMBIOS that does support it. For instance maybe use Mac Mini 8,1 or later. If you do this, you will need to follow the iGPU guides from Dortania. My experience is using SMBIOS with connector-less allows for better acceleration from your GPU. You also won't bump into issues with photoshop and adobe where it would not necessarily pick the correct GPU for processing photos, rendering etc. The advantages of using connector-less SMBIOS outweigh the negatives if you have Dedicated GPU.

**Comment by peternguy3n** [comment]
I agree with @kwuster, but can confirm that i9 iGPU works with SMBIOS iMac19,1 since I am using that CPU as well. I originally had the iGPU in non-connectorless mode, which seemed to work fine along with my RX 580 card. I switched to connector less for a cleaner setup.

**Comment by sowson** [comment]
I need the iGPU because I am doing Ph.D. studies and the issue I have with iGPU (i9-9900K) and 2 x AMD Radeon VII is as follows. When I have one AMD Radeon VII connected to monitor then screen "slow down" because GPU is on full load pressure by training od Deep Neural Network... So, I did that: 
![Screen Shot 2020-05-29 at 8 56 17 AM](https://user-images.githubusercontent.com/33941184/83242978-8914ca80-a19d-11ea-8e42-72b1b2743daa.png)
And it is because of those settings:
![Screen Shot 2020-05-29 at 11 16 03 AM](https://user-images.githubusercontent.com/33941184/83243151-ced19300-a19d-11ea-8586-ae05337c2a97.png)
It works partially because I can run OpenCL and it works pretty nice on GPU. But the issue I still have is that when I connect the monitor via HDMI or Display Port it is an only black screen... btw, I am using the macOS Catalina 10.15.5...
Any idea of how to make connectivity? I tried by many restarts below how to:
https://github.com/dortania/OpenCore-Desktop-Guide/blob/master/extras/gpu-patches.md
unfortunately, it does not work as expected on any "port mapping".
So... I do not have more ideas... :-/ Thanks for support so far!

**Comment by kwuster** [comment]
If your work is that important, why are you doing it on Hackintosh? 
Just saying.

I don’t have the hardware you are using, but it pays to make sure iGPU is working first before adding in your GPU.

Have you looked in your bios settings to see if your initial display device is iGPU? not PEG? 

I’ve heard there were some issues with the RadeonBoost.kext on 10.15.5. Strip your kext list down to bare essentials.

Let’s put your PhD knowledge to good use and scientifically/ logically work the problem shall we?

You have too many things going on at once.

**Comment by sowson** [comment]
The only reason to make Hackintosh RIG is money... simply MacPro 2019 is $20k - $25k... I do not have as much... so I build $5k Hackintosh to do the work... sad but I do not have support on this and I wrote to Apple for some sponsorship but their not respond... Thanks for your help!

**Comment by sowson** [comment]
Thank you very much for your help... :-), I tried so many times changed some values in "config.plist" that I do not know why it works at the end :-)...
![Screen Shot 2020-05-30 at 9 03 41 PM](https://user-images.githubusercontent.com/33941184/83337399-3a5d5280-a2bb-11ea-9b44-f1a1ae8bac6c.png)
Thank you!

**Comment by sowson** [comment]
Sorry to add a comment, but you maybe wonder pictures and spec ;-)... It is at https://iblog.isowa.io/2020/05/31/ph-d-hanna-hackintosh-is-ready/
Thanks a lot!

**Comment by sowson** [comment]
I am sorry to bother you again, but on the above rig I put my EFIs on the https://github.com/sowson/hannapc and I have DisplayPort working and I am glad to use it but HDMI not... I was looking how to enable it entire weekend and I gave up... can you take a look? @peternguy3n @kwuster any ideas you may share with me? Thanks!
