### ISSUE TITLE
can't access bios

### ISSUE THREAD

**Issue by marcoecheverria** [czombos/asus-rog-strix-z390-i-gaming#24]
Asus Rog Strix Z390 I-Graming Mobo
Intel Core i7 9700K
Corsair Vengeance LPX 3200 MHz DDR4 (2 x 16 GB)
WD Black NVMe M.2 SN750, 1 TB - Hackintosh - OpenCore
Samsung 970 EVO NVME M.2 - 500 GB - Windows 10 Pro

It was working perfectly but since I installed opencore I can not access the BIOS. I tried everything (I used Displayport and HDMI cables in the mobo's HDMI and in the GPU. I always can see the logo and when I press F2 or DEL it goes to a black screen.

It was ok but today I decided to add another SSD 2.5 drive to clone my Hackintosh drive and I have message asking me to get into the BIOS. I decided to perform a CMOS reset, it doesn't work ...same problem...then I decided the disconnect the CMOS battery. Same. I can see the logo but when I press F2 or DEL ...black screen. Is my motherboard faulty? any ideas.

NOTE: thanks for your notes. It helped me a lot. It was working perfectly but no access to the BIOS.

**Comment by marcoecheverria** [comment]
I am getting this message: https://www.dropbox.com/s/7z4hsyxtonnxxwo/IMG_4932.jpg?dl=0

**Comment by czombos** [comment]
please turn off secure boot

**Comment by marcoecheverria** [comment]
thanks for the quick response. How can I turn off secure boot if I can't access the BIOS.

**Comment by peternguy3n** [comment]
If you can boot into Windows, download AI Suite 3 and flash your bios again. That will fix it.

**Comment by marcoecheverria** [comment]
Thanks a lot. Exactly. I found a post that helped me to solve the problem. During the Opencore installation, something happened that created a problem in my BIOS. I followed this guide and it helped me to reinstall the latest BIOS firmware from Windows. Here is the link: [https://forums.tomshardware.com/threads/black-screen-when-trying-to-start-uefi-bios.3489380/post-21390711](url). Thanks a lot. @czombos thanks for all your help with this guide.

**Comment by marcoecheverria** [comment]
@crowbarska @Petek16

I solved the problem it comes from nvram faulty you need to reflash your nvram but in asus devices bios upgrade installing into bios itself so if you want to reflash from windows you need to install it with ami bios tool
First of all its a reinstalling bios from AMI for all AMI bios devices if something goes wrong I am not responsible for any of that. But I test it almost 10 times. It happens on me because of hackintosh for you reason might be different.
Solution:
1-) Download latest bios for your device from asus web site
2-) Download AMI bios tool from bios mods link is in here: AMI BIOS
3-) Open that with administrator privilages Aptio\afuwin\64\AfuWin64\AFUWINGUI.exe
4-) Click open chose all files for file type from down right and select your ACCURATE BIOS FILE FOR YOUR DEVICE FROM ASUS.
5-) Click Setup Select Main Bios Image, Boot Block and NVRAM( You can choose just NVRAM but I dont recommended)
6-) Click Flash and make sure you have connected your PC to AC power.
7-) Restart. It takes few restart to install bios wait for 1 or 2 min top. Then all will be ok
