### ISSUE TITLE
BCM94360NG - Asus Z390-E

### ISSUE THREAD

**Issue by kujtimiihoxha** [czombos/asus-rog-strix-z390-i-gaming#29]
Hi, I am just curios to know if you have replaced the default wifi card with the `BCM94360NG` and if you did anything to make it work?

I have an Asus Z390-E that had an `Intel 9560NGW` by default, I got a [BCM94360NG](https://www.aliexpress.com/item/4000631796433.html?spm=a2g0s.9042311.0.0.26ec4c4dIlwmWk) and for some reason it not being detected by the os at all.

I don't really know how to test if the card is a defective card or if the motherboard does not support it.

Appreciate any suggestions :)

**Comment by rajeevhans** [comment]
That card is Natively suppored by Mac OS. I know Gigabyte motherboards prevent you from swapping out the Intel based card but in my experience I've never had an issue with Asus motherboards.

Do you have windows/linux to verify if the card is actually functioning?

**Comment by kujtimiihoxha** [comment]
I tried booting to a linux distro and the card was also not discovered, I assumed that the problem is that the card is a broadcom card and I now from before that those cards don't have good support on linux.

My other thought is that I have been reading about `CNVI` and it turns out that the native wifi card is actually a `CNVI` card.

I will try to boot into linux again and check if I can install some broadcom drivers and see if the card shows up.

**Comment by rajeevhans** [comment]
Yeah most Intel motherboard these days come with CNVI with most processing done by CPU/Chipset. Having said that Broadcom cards work just fine on at least Asus/AsRock motherboards. Find out if you at least see the card in Linux/Windows - otherwise it could be DOA.

**Comment by kujtimiihoxha** [comment]
Yeah I think it is a dead card, or I have installed it wrong (which should be pretty hard it either fits or not 😂 ). 

I can't see it in linux not even as a PCI device

**Comment by sowson** [comment]
Sorry to comment on this but I have Z390-E and M.2 Wifi + BT card does not work, but I used Hackintosh BCM94360CD Wi-Fi 802.11ac Bluetooth 4.0 on last bottom PCI-E slot and it works perfectly. So, I check on 3 cards including one that I am 100% sure it works, and Z390-E does not detect it at all. So, the only thing maybe a BIOS upgrade someday, but for now, it does not work. Thanks!

**Comment by kujtimiihoxha** [comment]
@sowson thanks for the info really interesting, I just wasted 50$ then 😂
