### ISSUE TITLE
Bluetooth issue

### ISSUE THREAD

**Issue by alfredo-villa** [czombos/asus-rog-strix-z390-i-gaming#3]
Hi, i have some problem with my DW1820A, your clover configuration and Catalina OS.
The bluetooth device board is recognized but I cannot connect any external device (keyboard, mouse, etc,.) Do you have any advice on this?
Thanks

**Comment by czombos** [comment]
The DW1820A cards are problematic so I do not recommend using them. Here's how it works:
Turn off the computer and unplug the power cord, and then wait 5-10 minutes. 
Start an installed Windows 10 and install the official DELL driver for it: [Dell Wireless 1820A Bluetooth Driver](https://www.dell.com/support/home/en/hubsdt1/drivers/driversdetails?driverid=99v46&oscode=wt64a)
Pair a Bluetooth device.
You can then reboot your PC and then you can successfully pair your device with macOS.

**Comment by alfredo-villa** [comment]
Thank you so much, your suggestion worked perfectly.
