### ISSUE TITLE
No EUFI booting appears 

### ISSUE THREAD

**Issue by rpzrpzrpz** [czombos/asus-rog-strix-z390-i-gaming#5]
After you issue the "create media" command to create a USB installer, I am not able to get the Z390 to acually show in the BIOS boot setup for ROG-STRIX-z390-i-gaming.

What are you doing after USB installer creation?

This is for OpenCore, not clover.

I have a Ubuntu linux and it shows on the same port just fine.

**Comment by czombos** [comment]
[Follow this guide](https://khronokernel.github.io/Opencore-Vanilla-Desktop-Guide/installer-guide/opencore-efi.html)
