### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by ladit** [czombos/asus-rog-strix-z390-i-gaming#6]
Thanks for the dedicated working! I have some issues:

## Please update the EFI

I notice that you may populated the config.plist from the `Sample.plist`. But there may be some unrelated properties, such as some `Block` and `Patch` fields. Moreover, I compared the file size of  kexts and UEFI drivers. They are not the same as the latest version.

`VBoxHfs.efi` should be removed because of `HFSPlus.efi` is included.

`VirtualSmc.efi` is said to be merged into `OpenCore.efi` and should be removed.

## About the DSDT/SSDT

I am curious about what part and how the DSDT of z390i or any other motherboard should be patched, are you just following [this page](https://khronokernel.github.io/Opencore-Vanilla-Desktop-Guide/extras/acpi.html) or is there another tutorial?

Thanks again!

**Comment by czombos** [comment]
#[Fixed](https://github.com/czombos/asus-rog-strix-z390-i-gaming-hackintosh/commit/0b495ef286d2487199203453b5fae40524b986c3)
