### ISSUE TITLE
iGPU not recognizing with Opencore EFI

### ISSUE THREAD

**Issue by quanngo2304** [czombos/asus-rog-strix-z390-i-gaming#7]
Hi,
I’m using you EFI but my CPU is i7 9700k but I’m not sure that iGPU UHD 630 recognized by MacOS. 
Maybe something wrong?

**Comment by theartkod** [comment]
if no laggy interface - it already work 😄

**Comment by czombos** [comment]
You can check it in Hackintool: 
https://www.insanelymac.com/forum/topic/335018-hackintool-v286/

Read this guides:
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md
https://khronokernel.github.io/Opencore-Vanilla-Desktop-Guide/extras/gpu-patches.html#igpu-busid-patching
