### ISSUE TITLE
OpenCore bootloader not loading

### ISSUE THREAD

**Issue by theartkod** [czombos/asus-rog-strix-z390-i-gaming#8]
hey, thank you for guide! it work with clover(almost) on a similar hardware, but opencore bootloader not work. when i boot from usb - i see only EFI shell, and even when i manually load BOOT file, it throw error 'OC: nested ReRun is not supported'  

ps. i just copy&paste your opencore configs to my EFI partition of usb disk, because hardware very similar, and motherboards identical.

**Comment by czombos** [comment]
I don't know exactly what the problem is.
This link may help:
https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?page=88
